### PR TITLE
Minor changes and formatting for BNPB QGIS training

### PR DESCRIPTION
**Pull request by Charlotte-Morgan**
Please check carefully before merging. Track changes recorded but not shown.
 Changes to be committed:
	modified:   QGIS/section1-intro/1-qgis-navigating-map-data.odt
	modified:   QGIS/section1-intro/qgis-attribute-data-basics.odt
	modified:   QGIS/section3-symbology/qgis-styling-basics.odt
	modified:   QGIS/section5-labelling/7-qgis-rule-based-labels.odt
	modified:   QGIS/section6-composer/qgis-composer-atlas.odt
	modified:   QGIS/section6-composer/qgis-composer-basics.odt

Two comments from my attempt to do the training:
Question about answer in composer-atlas
Question about expression in rule based labels. Other = ELSE

### CODE REVIEW

**Comment by Charlotte-Morgan** [comment]
@timlinux please review when you have time so that I know if this workflow is ok for the review of other worksheets and also so DMI can start the Indonesian translation

**Comment by timlinux** [comment]
modified: QGIS/section1-intro/1-qgis-navigating-map-data.odt

@gubuntu but I don't think making user work with plugins in the very first sheet they do makes sense.

**Comment by timlinux** [comment]
> Question about expression in rule based labels. Other = ELSE

in this case the expression does not validate in the expression editor, just type it directly in the rule's expression. It is a catch all for all unmatched features.

**Comment by timlinux** [comment]
@Charlotte-Morgan and @gubuntu FYI

I had a look through the changes @Charlotte-Morgan made. I am ok to go with her approach for now. I would prefer to have the exercise and requirements fit completely on the first page if possible but its not a show stopper for now. @gubuntu FYI I am thinking that we should move the CMS part of this into projecta (Not DMI funded) in the near future - we should be able to gain translation support in that way and also manage the content production/layout digitally.

@Charlotte-Morgan are you proposing that we redo all of the sheets in your proposed layout? I don't know if it is effective for us to spend time doing that - though I am happy that we use either the "bullets first, specification second" approach or the "bullets left, specifications right" approach as needed.

@Charlotte-Morgan regarding your query on this Q&A:

2. What will happen if you delete one of the grid polygons from your coverage layer?
a) QGIS will give an error message
b) The atlas will not mask the surrounding features
c) The atlas page for that feature will be skipped

C is the correct answer -  the atlas iterates over the coverage layer so if you delete a feature it will be skipped.

@gubuntu @NyakudyaA I think the content generally needs more review - please continue to tweak and fix typos etc. during your training courses.

Lastly @Charlotte-Morgan we should provide PDF's with each ODT so it is easy to dip in and grab them from Git. @NyakudyaA maybe we can make a script to do that....something like: 


```
libreoffice --headless --convert-to pdf *.odt
```

Lets go ahead and merge @Charlotte-Morgan and we will take care of the PDF generation.

**Comment by Charlotte-Morgan** [comment]
hi @timlinux - thanks for review.
`@Charlotte-Morgan are you proposing that we redo all of the sheets in your proposed layout? I don't know if it is effective for us to spend time doing that - though I am happy that we use either the "bullets first, specification second" approach or the "bullets left, specifications right" approach as needed.`
No, not suggesting this at all. The change in layout was to improve readability (IMO) and consistency of fonts. 

Looks like my Q on Q&A was on the wrong question. There is one about making a QGIS movie from atlas.

Re translation & PDF generation - DMI will take merged files (in English) translate and generate a new set of files with _ID in the name. It will be these that need to be made into PDF for the training courses.

**Comment by Charlotte-Morgan** [comment]
Will someone please accept changes and merge so that we can then take the files for translation?

**Pull request merged**
